version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7.17-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

volumes:
  rabbitmq: {}
